### ISSUE TITLE
Deployment on Heroku does not work

### ISSUE THREAD

**Issue by gbhn** [kalanakt/Url-Uploader-TG#1]
```
2021-11-02T04:23:32.145687+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`
2021-11-02T04:23:32.907590+00:00 heroku[worker.1]: State changed from starting to up
2021-11-02T04:23:33.868917+00:00 app[worker.1]: 2021-11-02 04:23:33,868 - pyrogram.crypto.aes - INFO - Using TgCrypto
2021-11-02T04:23:33.936472+00:00 app[worker.1]: 2021-11-02 04:23:33,936 - asyncio - DEBUG - Using selector: EpollSelector
2021-11-02T04:23:35.169968+00:00 app[worker.1]: Pyrogram v1.0.7, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
2021-11-02T04:23:35.169989+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-11-02T04:23:35.169989+00:00 app[worker.1]: 
2021-11-02T04:23:35.742932+00:00 app[worker.1]: Traceback (most recent call last):
2021-11-02T04:23:35.742947+00:00 app[worker.1]:   File "bot.py", line 38, in <module>
2021-11-02T04:23:35.743084+00:00 app[worker.1]:     app.run()
2021-11-02T04:23:35.743096+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
2021-11-02T04:23:35.743233+00:00 app[worker.1]:     self.start()
2021-11-02T04:23:35.743243+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-11-02T04:23:35.743393+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-11-02T04:23:35.743411+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2021-11-02T04:23:35.743766+00:00 app[worker.1]:     return future.result()
2021-11-02T04:23:35.743768+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2021-11-02T04:23:35.743901+00:00 app[worker.1]:     await self.initialize()
2021-11-02T04:23:35.743912+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2021-11-02T04:23:35.744020+00:00 app[worker.1]:     self.load_plugins()
2021-11-02T04:23:35.744030+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client.py", line 724, in load_plugins
2021-11-02T04:23:35.744395+00:00 app[worker.1]:     module = import_module(module_path)
2021-11-02T04:23:35.744397+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-11-02T04:23:35.744500+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-11-02T04:23:35.744528+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-11-02T04:23:35.744629+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-11-02T04:23:35.744686+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-11-02T04:23:35.744745+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-11-02T04:23:35.744810+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2021-11-02T04:23:35.744905+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-11-02T04:23:35.744978+00:00 app[worker.1]:   File "/app/plugins/youtube_dl_echo.py", line 10, in <module>
2021-11-02T04:23:35.745121+00:00 app[worker.1]:     import lk21, urllib.parse, filetype, shutil, time, tldextract, asyncio, json, math, os, requests
2021-11-02T04:23:35.745177+00:00 app[worker.1]: ModuleNotFoundError: No module named 'lk21'
2021-11-02T04:23:36.029808+00:00 heroku[worker.1]: Process exited with status 1
2021-11-02T04:23:36.093403+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by kalanakt** [comment]
fixed it , demo bot : https://t.me/turbotheuploaderbot
